import { Inter, Bebas_Neue } from "next/font/google";
import "./globals.css";


const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-inter"
})

const babasNeue = Bebas_Neue({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-bebas"
})



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script src="https://kit.fontawesome.com/5eed2da627.js" aria-hidden="true" crossOrigin="anonymous"></script>
      </head>
      <body className={`${inter.variable} ${babasNeue.variable}`}>
        {children}
      </body>
    </html>
  );
}
